### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by ibilux** [ProteanSoftware/capacitor-firestore#1]
Hello @ProteanSoftware,
Can you the `@capacitor/core` from `"^3.0.0"` to latest `"^4.3.0"` ?
```
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @proteansoftware/capacitor-firestore@0.1.3
npm ERR! node_modules/@proteansoftware/capacitor-firestore
npm ERR!   @proteansoftware/capacitor-firestore@"*" from the root project

```

**Comment by AshleyMedway** [comment]
Sure I can update this tomorrow morning

**Comment by AshleyMedway** [comment]
`npm i @proteansoftware/capacitor-firestore@4.0.0` to install the version with capacitor 4 support.

Untested so let me know if it works, same changes we made in our other plugins so should be okay.

https://www.npmjs.com/package/@proteansoftware/capacitor-firestore/v/4.0.0

**Comment by ibilux** [comment]
@AshleyMedway Thank you.
I will test it and provide a feedback if there is any issues.
